# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: faec6b465215a98e91fbff874b790a51e7cee3d20a3b447284e9f90b6e3e3b490b2670937af4593c6d4c0a162f6cd9fe1a31ed142d17d518deb1166b5fe084ca

test:
  secret_key_base: bd18df70ebfef4d7cbd19e7910c3028f633ff5efa56080dbbb73835063dd101243f339273dfd9d2c2f6f1f27d69b7c8d8c6dcf5f17325157c3da9c10c3fbb194

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
